Fix breakage with the latest Plone Security Hotfix
smcmahon/Products.PloneFormGen pull request #229
Opened 2021-05-19 11:21 UTC by dhavlik

With the latest plone security hotfix (Products.PloneHotfix20210518), traversal to names starting with _ is forbidden.
As we do only want names starting with persistent_ here, we can safely ignore anything starting with _ and do not try to get it from the request.

2021-05-19 22:06 UTC, mauritsvanrees requested changes
I have just released version 1.2 of the hotfix, which addresses this. But this is a special case for Plone only (it is about the `_authenticator` key), and when this gets merged into core Zope, I can imagine they want to remove the special case. So it would be good to have a fix in PloneFormGen anyway.

I have not tried it, but looks like your PR fixes the problem.

But it can be done a bit more efficient (just like the original code could have been more efficient): in your new code remove the first condition and replace it with the second condition.

2021-05-24 13:21 UTC, MrTango commented
This patch also prevents the missing _submit error when the form validation hits.
Can we please get this merged and released soon?

2021-05-25 09:11 UTC, spereverde commented
I copied this fix for the 1.7-maintenance version as well: 
https://github.com/smcmahon/Products.PloneFormGen/pull/230

@mauritsvanrees could you please check that this adjusts the conditions as you asked for in this PR? let me know if I should change anything, thanks!

2021-05-26 17:49 UTC, alecpm commented
This fix will also address issues with loading forms in modals created by the Hotfix. Specifically, jQuery AJAX requests add a cachebusting request variable named `_` to the query string which breaks form rendering with the hotfix.

@mauritsvanrees perhaps the hotfix should skip the `_` name check when looking at keys in dictionary objects like `request.form`. I don't think such checks provide a security benefit, and I have already seen issues on a couple of production sites today related to this.

2021-05-27 08:02 UTC, merged

2021-05-27 08:43 UTC, mauritsvanrees commented
I have released 1.8.9 and 1.7.27.

2021-05-27 09:38 UTC, mauritsvanrees commented
@alecpm Are your problems only with PloneFormGen or also with other packages? Is there a community package you can point to, or share a code snippet?

We could allow accessing underscores in a dict. But it would likely still need some changes in add-ons.

- `request/_test` would still give a NotFound, like now.
- `request/_test|nothing` would return nothing, like now
- `request/form/_test` would still fail: the hotfix code would use `request` as base, and still fail when iterating over the two path items.
- `tal:define="form request/form; value form/_test;"` would work then, because we traverse in two parts: we first traverse from request to form, which is obviously fine, and then we traverse from the form dictionary to `_test`, which we would then allow.

So this might solve some problems, but in most cases probably still requires a fix in the add-on. But at least this offers a way around the problem.